name: Run Python Files on Push

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  python-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Run hello.py
        run: python hello.py

      - name: Run calculate.py
        run: python calculate.py

      - name: Run data_process.py
        run: python data_process.py
